### ISSUE TITLE
problem with enum types

### ISSUE THREAD

**Issue by yannick** [msgpack/msgpack-d#60]
not sure if this should be supported and its not really a big problem but none the less i wanted to put it here:

```
enum A : string {  one = "ONE", two = "TWO"} 
class Example
{
  @property A a;
  @property string b;
}
```
this fails

```
../msgpack-d/src/msgpack.d(856): Error: forward reference to inferred return type of function call pack(f)
../msgpack-d/src/msgpack.d(862): Error: forward reference to inferred return type of function call pack(f)
../msgpack-d/src/msgpack.d(115): Error: template instance msgpack.PackerImpl!(Appender!(ubyte[])).PackerImpl.pack!(Ack) error instantiating
```

**Comment by repeatedly** [comment]
Sorry for late response.

I got other errors but I confirmed enum with string doesn't work on 2.067.1.
I will check it later.

```
src/msgpack.d(949): Error: msgpack.PackerImpl!(Appender!(ubyte[])).PackerImpl.pack called with argument types (A) matches both:
src/msgpack.d(706):     msgpack.PackerImpl!(Appender!(ubyte[])).PackerImpl.pack!(A).pack(const(A) value)
and:
src/msgpack.d(742):     msgpack.PackerImpl!(Appender!(ubyte[])).PackerImpl.pack!(A).pack(const(A) array)
src/msgpack.d(955): Error: msgpack.PackerImpl!(Appender!(ubyte[])).PackerImpl.pack called with argument types (A) matches both:
src/msgpack.d(706):     msgpack.PackerImpl!(Appender!(ubyte[])).PackerImpl.pack!(A).pack(const(A) value)
and:
src/msgpack.d(742):     msgpack.PackerImpl!(Appender!(ubyte[])).PackerImpl.pack!(A).pack(const(A) array)
src/msgpack.d(875): Error: template instance msgpack.PackerImpl!(Appender!(ubyte[])).PackerImpl.packObject!(Example) error instantiating
src/msgpack.d(141):        instantiated from here: pack!(Example)
issue60.d(15):        instantiated from here: pack!(false, Example)
```

**Comment by repeatedly** [comment]
I wrote a patch > https://github.com/msgpack/msgpack-d/pull/64
Could you test it?
