### ISSUE TITLE
Fails with recent DMD

### ISSUE THREAD

**Issue by nordlow** [msgpack/msgpack-d#22]
msgpack.d no longer compiles with recent DMD because of https://github.com/D-Programming-Language/dmd/commit/7360ae8611add4dc0a89cd870a6ac6490fb2a19b

```
/home/per/Work/justd/msgpack.d(3869): Error: goto skips declaration of variable msgpack.StreamingUnpacker.execute.base at /home/per/Work/justd/msgpack.d(3930)
/home/per/Work/justd/msgpack.d(3876): Error: goto skips declaration of variable msgpack.StreamingUnpacker.execute.container at /home/per/Work/justd/msgpack.d(4051)
/home/per/Work/justd/msgpack.d(3880): Error: goto skips declaration of variable msgpack.StreamingUnpacker.execute.container at /home/per/Work/justd/msgpack.d(4051)
/home/per/Work/justd/msgpack.d(4026): Error: goto skips declaration of variable msgpack.StreamingUnpacker.execute.container at /home/per/Work/justd/msgpack.d(4051)
/home/per/Work/justd/msgpack.d(4031): Error: goto skips declaration of variable msgpack.StreamingUnpacker.execute.container at /home/per/Work/justd/msgpack.d(4051)
/home/per/Work/justd/msgpack.d(4036): Error: goto skips declaration of variable msgpack.StreamingUnpacker.execute.container at /home/per/Work/justd/msgpack.d(4051)
/home/per/Work/justd/msgpack.d(4041): Error: goto skips declaration of variable msgpack.StreamingUnpacker.execute.container at /home/per/Work/justd/msgpack.d(4051)
```
